#pragma once

// CoolQ
#define CQAPPID "org.dazzyd.cqsocketapi"
#define CQAPPINFO CQAPIVERTEXT "," CQAPPID

// Socket API
#define SERVER_PORT 11235
#define CLIENT_SIZE 32
#define CLIENT_TIMEOUT 300
#define FRAME_PREFIX_SIZE 256
#define FRAME_PAYLOAD_SIZE 32768
#define FRAME_SIZE (FRAME_PREFIX_SIZE + FRAME_PAYLOAD_SIZE + 1)